### ISSUE TITLE
Upload Speed test is too small

### ISSUE THREAD

**Issue by volure** [sivel/speedtest-cli#158]
I understand this may be an edge case, but I have a gigabit speed for my server, And I wanted to use this because linux does not do flash very well.

I have a gigabit fiber connection, and most of my tests os OSX are 940Mbit/940Mbit give or take 30 or so Mbit

However with this command line app, I am displaying from my linux box. 773Mbit/205Mbit which I know is very inaccurate because the upload lasts less than a second.

I have tried the --bytes param, but then I realized that is for display

**Comment by emerham** [comment]
Just got a network upgrade at work and I am also seeing the same thing. Definitely looks like a cap in the utility. Webpage version is showing correct data.

**Comment by NotANormalNerd** [comment]
From the first page:

# Inconsistency

It is not a goal of this application to be a reliable latency reporting tool.

Latency reported by this tool should not be relied on as a value indicative of ICMP style latency. It is a relative value used for determining the lowest latency server for performing the actual speed test against.

There is the potential for this tool to report results inconsistent with Speedtest.net. There are several concepts to be aware of that factor into the potential inconsistency:

 * Speedtest.net has migrated to using pure socket tests instead of HTTP based tests
 * This application is written in Python
 * Different versions of Python will execute certain parts of the code faster than others
 * CPU and Memory capacity and speed will play a large part in inconsistency between Speedtest.net and even other machines on the same network

Issues relating to inconsistencies will be closed as wontfix and without additional reason or context.

**Comment by Cha0sgr** [comment]
I confirm this issue. The upload test is way too small for any comprehensive results when the machine running the test has a really fast connection.

The upload test size should be at least configurable if not automatically changeable based on the download speed (I believe the flash client on the speedtest.net website calculates automatically how big the upload test should be based on the download speed).

Right now this tool, while extremely useful for slow connections, it's pretty much useless for fast connections.

@NotANormalNerd the issue described here is not about inconsistency due to Python versions or CPU/RAM. This is about [TCP slow start](https://en.wikipedia.org/wiki/Slow-start) and that's why speedtest.net will do larger tests on machines with faster connections.

When you have 1gbit or 10gbit uplinks, running an upload test of only a few mbytes it's impossible to measure how much bandwidth your uplink can handle since the test is completed in about a second or two, and [TCP slow start](https://en.wikipedia.org/wiki/Slow-start) will take up to a few seconds to fully fill the available bandwidth of the uplink.

I believe the easiest way to resolve this is to simply allow the user to define the test sizes to compensate for that.

**Comment by mellanon** [comment]
I too confirm this. I'd be happy to contribute to try to fix this though...

Found this speedtest.net under-the-hood guide:
https://support.speedtest.net/hc/en-us/articles/203845400-How-does-the-test-itself-work-How-is-the-result-calculated-

I've setup a single board computer (odroid) which is running Ubuntu 14.04.3 LTS. It's connected to a 200/100.

The upload test was way out to begin with, but by decreasing the number of threads to 4, increase the time of the test and increase the size of the files it's now only 15% off. Increasing the file size and test time might minimse the TCP slow start effect.

A few ideas to increase it further would be to:
1. Develop a method to decide the speed of the connection
2. Both the download and upload tests are configured based on the initial test.
3. Instead of timing the test from the start of the first thread being spawned to when the last thread is finished each thread is timed individually. The two fastest and the bottom 1/4 results are removed and the remaining results are averaged out (according to the algorithm described by the link above)
4. Don't spawn any more threads after the configured test period is over, but allow the running tests to finalise before ending the test.
5. I think the test result is affected negatively since the overhead of generating files to send is included in the overall test time. Timing each thread separately might solve this. Otherwise I was thinking that one could try to pregenerate the files to be sent instead of generating them on the fly to get rid of the overhead. I'm afraid that caching will kick in and distort the result though.
6. Input to the additions would be to have a closer look at how the speedtest.net test is executed using the browser. Wireshark to do some traffic analysis might be helpful. I.e. the link above mention that the browser based test is using four threads for connections above 4 Mbits otherwise two threads are used. How big is the chunks and buffer sizes depending on connection speed? Would be good input...

**Comment by Cha0sgr** [comment]
Great!

Unfortunately I am not familiar with Python so I am not able to contribute with code. 
I can do any beta testing though if anyone has the time to implement these changes :)

**Comment by sivel** [comment]
I do believe this is largely resolved.  I've made some changes between 1.0.5 and 1.0.6 to improve upload performance.

1.0.5
```
Ping: 15.549 ms
Download: 477.75 Mbit/s
Upload: 203.97 Mbit/s
```

1.0.6
```
Ping: 9.826 ms
Download: 482.68 Mbit/s
Upload: 526.11 Mbit/s
```
