### ISSUE TITLE
Can't test speed for arbitrary third-party server

### ISSUE THREAD

**Issue by YorkTsai2012** [sivel/speedtest-cli#220]
It seems that speedtest-cli only tests network speed between the local host and one of the speedtest.net servers
if the --server parameter is specified with www.google.com, it will fail, as follows.
```` 
[$] ./speedtest-cli  --server www.google.com
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from CloudVsp (123.59.80.121)...
Invalid server ID
```
Will speedtest-cli become more general that it also be able to test network speed to an arbitrary third-party server?
@sivel @panozzaj

**Comment by panozzaj** [comment]
Hi @YorkTsai2012! I am not a maintainer, just a user of the project, but I will try to help.

Currently it looks like the `--server` flag is used to specify a certain server *id* from the current speedtest servers list. You might be able to add arbitrary servers by modifying where the program looks for server lists or to override this flag or add another flag to do so. However, it seems like the server you specify must conform to a certain protocol or have certain endpoints to be able to correctly upload to and download files from it to test your connection speed. So putting an arbitrary third-party server won't work because it doesn't have those endpoints and work in the same manner. Also, it's may not be clear where the third-party server is located, and I think one of the values of speedtest is to reduce geographical distance between you and the server to take that away as a variable.

I can't say that this is not on the roadmap, but it seems that unless you had an open source speedtest server that it would be difficult to point to a third-party server. Hope this helps!

**Comment by sivel** [comment]
This functionality is definitely not supported nor on the roadmap.  This tool is for testing speed against speedtest.net, with the option of testing against a speedtest.net mini install also.
