### ISSUE TITLE
Would love option to just do an upload test without downloading

### ISSUE THREAD

**Issue by vincentwoo** [sivel/speedtest-cli#272]
The units used by the script appear to be set by the download speed. So, when throttling upload to something low, the script outputs:

```
Testing download speed........................................
Download: 66.11 Mbit/s
Testing upload speed..................................................
Upload: 0.00 Mbit/s
```

**Comment by runxctry** [comment]
While running risk of adding feature creep, this sounded like a useful feature, so I've implemented --noDL and --noUL flags (in my fork) to disable either test.  

I also relegated display of throughput to "fundamental" units of bps instead of Mbps when running with --simple.  This also seemed like a legitimate requirement.  There's probably a better way to implement this; ideas are (1) somehow in conjunction with --bytes, (2) specifying a --type command-line option, and/or using (3) python [filesize autoranging](http://stackoverflow.com/questions/5194057/better-way-to-convert-file-sizes-in-python).  Or any combination of the above, as time allows.

Regardless, user states he no longer requires this feature, and I have his suggestions implemented & committed in my fork.  I'll work with the author separately to pull them.

Recommending closure.

**Comment by hackruu** [comment]
👍

**Comment by tarwich** [comment]
@runxctry Have to tried to PR to see if they'll accept it?

**Comment by sivel** [comment]
This now exists in the current release
