### ISSUE TITLE
Improve accuracy of version 1.0

### ISSUE THREAD

**Issue by skiyuki** [sivel/speedtest-cli#344]
Thank you for your uploading the version 1.0 codes which make me joyful to try and modify the codes.
I increased speed prediction accuracy by the following modifications.

1) Increase upload chunk length
self.config['upload_max'](=50) chunks are selected from chunk list generated by 
for size in  [524288, 1048576, 7340032]:
   for _ in range(0, 33):
        sizes.append(size)
 
(524288 * 32 + 1048576 * 18) * 8 = 285.212672 Mbits without 7340032 chunk.
Modify to,
for _ in range(0, 33):
    for size in  [524288, 1048576, 7340032]:
        sizes.append(size)
((524288 + 1048576 + 7340032) * 16 + 524288 + 1048576) * 8 = 1153.4336 Mbits

2) Increase timeout
Timeout is fixed to self.config['length']['upload'](=10 seconds), is not changed by
 --timeout command options. Download timeout occurs when speed is lower than 3275/10=327Mbits/second, lowering speed decreases download chunks and may lower accuracy.

Set self.config['length']['upload'] to the lowest speed of target systems.

3) Simplify join()
It may be a little improvements, however easy to understand.

3.1) No thread.join(timeout=0.1)
Thread flows are controlled by the following lines:
thread = q.get(True)
while thread.isAlive():
   thread.join(timeout=0.1)
whitch can be replaced　by
thread = q.get(True)
thread.join()

Overheads of q.get(), counted as the longest thread run time divided by 0.1, may be removed.

3.2) No pro_thread.join()
Producer and consumer threads are synchronized by a Queue.
The following lines 
while prod_thread.isAlive():
    prod_thread.join(timeout=0.1)
while cons_thread.isAlive():
    cons_thread.join(timeout=0.1)
are replaced by 
cons_thread.join()

How about the above modifications?

**Comment by sivel** [comment]
Yeah, so I won't lie.  That is too much text for me to read.

For one, some of the logic is duplicated from the logic that speedtest.net uses, so I'm likely not modifying some of that.  Such as 1 and 2.

For 3, I'm not likely to change that, as some of the reasoning behind using a join with a timeout is so that I can properly interrupt the process. Perhaps the timeout could be reduced, but I'm not convinced that you are really going to see much of an improvement.
