### ISSUE TITLE
Can't pipe

### ISSUE THREAD

**Issue by powmonk** [sivel/speedtest-cli#349]
I get the following when I run "./speedtest --simple | cat speedresult"

**close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr**

It would be handy if I could set a cron job to record my speed.

**Comment by sivel** [comment]
I'm not sure what your command is trying to accomplish.  You are piping the output of `./speedtest --simple` into `cat speedresult` which doesn't really do anything useful, since `cat speedresult` prints out the contents of `speedresult`.

The way your command is executed is actually `cat speedresult` runs first, which terminates the listening socket from the pipe, and then when `./speedtest --simple` completes, it fails with some form of broken pipe error, which I guess is what is happening to you.

Maybe what you really wanted is `./speedtest --simple > speedresult`

**Comment by powmonk** [comment]
Yeah, my bad. It's been a while since I've used bash. Ignore me
