### ISSUE TITLE
Recent serveres belonging to speedtest.net (>10300) show wrong ping/ no download result

### ISSUE THREAD

**Issue by chriswayg** [sivel/speedtest-cli#416]
Recent servers belonging to speedtest.net 
numbered 10300 show wrong ping and no download result

also tried 10392 10395 etc.

`speedtest-cli --version`
1.0.6

EXAMPLE:
```
$ /usr/local/bin/speedtest-cli --server 10384
Retrieving speedtest.net configuration...
Testing from Globe (180.191.87.149)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Speedtest.net (San Jose, CA) [11281.30 km]: 1800000.0 ms
Testing download speed................................................................................
Download: 0.00 Mbit/s
Testing upload speed................................................................................................
Upload: 4.82 Mbit/s
```

**Comment by supremeliter** [comment]
This happens on specific servers.  My Washington DC server returns all 0s on each 'self.result.append(len(f.read(10240)))' but the Beltsville, MD works.  I'm guessing Matt isn't in control of the test servers so the fix may need to be clever.  Maybe if the list is all 0, try the next best?

To assist, my working URL is blt.speedtest.t-mobile.com:8080
My non-working URL is wdc.speedtest.net:8080

I'll fork it later if I get a chance since Matt is on sabbatical.

**Comment by supremeliter** [comment]
Okay, got the latest version.  The 1800000.0ms is the result of a bad server and that's what happens to my bad DC one.  Since you're specifying a bad -- or at least incompatible -- server then the test won't work.  Is there a specific reason you insist on using that server?  This may actually be an issue with the server... but I'm hardly a rookie at this so don't take my word for it.

**Comment by chriswayg** [comment]
I tried various servers hosted by 'Speedtest.net' and they were not working, so I guess, that these servers did something to make them incompatible with speedtest-cli. - Testing these today, these same servers are working again.

```
$ speedtest-cli --server 10384
Retrieving speedtest.net configuration...
Testing from Globe (180.191.127.177)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Speedtest.net (San Jose, CA) [11281.30 km]: 210.805 ms
Testing download speed................................................................................
Download: 15.67 Mbit/s
Testing upload speed................................................................................................
Upload: 7.42 Mbit/s
```
