### ISSUE TITLE
Single thread

### ISSUE THREAD

**Issue by pgbicho** [sivel/speedtest-cli#533]
When comparing with web version, there I can reach almost 1Gbps, when on cli version results doesn't go over 500 Mbps.
This is because cli doesn't get the buffers full by using one single download thread.

Is it possible to implement multi thread option?

**Comment by smartbsd** [comment]
I't be great to know a little bit more about your reasoning and thinking before closing issues Sivel.

I see a very good point on the question and suggestion made by pgbicho at least in my short understanding of the tool and I've seen a couple of issues closed today but if there is no explanation about why you close them would like like no more development will be done in this project.

**Comment by dupuisv** [comment]
I have same problem, the results are wrong, i open an issue, it also get closed. i dig a little in the code. 
For me they are error because multiple thread are started, but the ones that download the biggest images from the speedtest-server get interrupted and the partially downloaded data get ignored. 

With a fastest speed link , the result get worse.

Maybe Sivel can tel us how to fix it, i can do the testing.

Regards
