### ISSUE TITLE
[Feature Request] Add an option to bind to some interface

### ISSUE THREAD

**Issue by jsalatiel** [sivel/speedtest-cli#573]
Would it be possible to add an option to bind to some interface? Like ping -I option.
I know that there is an option --source, but if the interface has a dynamic IP I always need to get the IP first, so it would be nice if I could just use -I or --interface eth0/eth1/eth2 ...
thanks!

**Comment by sivel** [comment]
Unfortunately, this is not something that I plan on adding. I had an early version that worked, but it was only compatible with Linux, and due to the vast array of operating systems this supports, it is not feasible to implement.

I'd recommend a little shell magic to get the IP which you would pass to `--source`.
