### ISSUE TITLE
Speed Test not reliable anymore

### ISSUE THREAD

**Issue by sscholl** [sivel/speedtest-cli#588]
Hello,

since 3 days, the speedtest does not give correct results anymore. Seems like speedtest.net is not working anymore with the script. When i measure by web browser it works.

![image](https://user-images.githubusercontent.com/2964060/54453525-ca1aed80-4757-11e9-8b52-f2a4c8e81164.png)
```
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Versatel Deutschland (94.134.156.231)...
Selecting best server based on latency...
b'Hosted by NetCologne (Cologne) [24.84 km]: 23.552 ms'
Testing download speed........................................
Download: 8.49 Mbit/s
Testing upload speed..................................................
Upload: 3.22 Mbit/s
```

![image](https://user-images.githubusercontent.com/2964060/54453657-0e0df280-4758-11e9-8b32-8d9e784de066.png)

**Comment by bmn-m** [comment]
Same results here. 
![Screenshot_20190316-102201__01](https://user-images.githubusercontent.com/18091782/54473262-8cf54080-47d5-11e9-8553-597d837fec8d.jpg)

**Comment by sscholl** [comment]
Why did you close? is it fixed?

**Comment by bmn-m** [comment]
Am i missing something? Why is the issue closed?

**Comment by takeda** [comment]
@sivel is there a reason why this is closed? I came here because I recently switched ISP and was using to test speed on my machine. speedtest-cli was consistently reporting that I'm getting half the speed I was subscribed to. I spent few days troubleshooting the issue, trying different tuning parameters, looking on bug reports for FreeBSD (version 12.0 had some refactoring around driver for the NIC I was using), trying different NICs and eventually observing interface parameters while a test was run to realize that speedtest-cli was reporting the wrong value.
