### ISSUE TITLE
macOS unable to run

### ISSUE THREAD

**Issue by tyhunter** [sivel/speedtest-cli#598]
Hi 
    I have some problem on macOS Speedtest-cli,it shows:

➜  ~ speedtest-cli
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: <urlopen error ('_ssl.c:711: The handshake operation timed out',)>

   and the version is 2.1.1

**Comment by sivel** [comment]
I cannot duplicate this, however this error is usually caused by having a version of OpenSSL that is old, which macOS has historically used.

This is not a problem that I can work around, the work around would be to upgrade to a newer macOS, or attempt compiling python against a newer OpenSSL, or obtaining your python from another source.
