### ISSUE TITLE
Login to speedtest.net

### ISSUE THREAD

**Issue by golfdanc** [sivel/speedtest-cli#607]
Hi,
I'm a rookie with Github and didn't know how to request a new feature for speediest-cli.  Here goes : If speediest-cli had the option of logging into speedtest.net, then results would be saved by speediest.net.  Then if there was any issues with download speeds, the results could be shared with the internet provider as proof.

Agree?

ps. I'm not a python programmer otherwise I would try adding this myself.

**Comment by sivel** [comment]
This has been attempted several times in the past, but the implementation was fragile, because it depended on interacting with the speedtest.net UI, and retrieving a cookie. This means that any change in the speedtest.net web UI would break that functionality.

As such, such a feature will not be included.

This application provides machine readable outputs via `--json` and `--csv` that can be used to log data and create graphs.
