### ISSUE TITLE
It's showing 0.00 Mbit/s

### ISSUE THREAD

**Issue by nunoleite** [sivel/speedtest-cli#665]
Hi!

I Run:
`curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -`

This used to work, but i noticed that some weeks ago it started to show 0.00 Mbit/s.

![Image 1](https://user-images.githubusercontent.com/173281/68286243-b02c7300-0078-11ea-9c66-a0b85bba0243.png)

Thanks

**Comment by sivel** [comment]
The key here is the latency number of 1800000.0ms.

That indicates that no server could be tested, and that all latency checks failed.  

This indicates that you are unable to communicate with the speedtest server.

**Comment by albatrozdigital** [comment]
Hi!
Thanks for the information. I did found that the problem is that i have port 8080 blocked by csf firewall.
Did this behavior changed?
Is it possible to use port 80?
Thanks

**Comment by sivel** [comment]
The remote port to use is dictated by the individual servers that speedtest.net uses, there is no functionality that could be implemented in this tool to change that.

**Comment by albatrozdigital** [comment]
Ok, thanks.

**Comment by rdkgit** [comment]
Hey!

I had this problem too.  See #640  The issue was closed w/o much info other than the issue was on my end.  Nothing that I'm aware of changed on my end. I tried digging through the code to see what ports were being used to test latency.  Turns out, unblocking outgoing port 8080 solved my problem of determining latency and then speedtest-cli started working again reporting accurate numbers.

Bobby
