### ISSUE TITLE
Can i set a python version for speedtest-cli?

### ISSUE THREAD

**Issue by NBSOD** [sivel/speedtest-cli#670]
As i said,default my speedtest-cli version is 2.1.2 and i want use python 2.x for my speedtest. What should i do ?(my server installed python 2 and 3 )

speedtest-cli  --version
speedtest-cli 2.1.2
Python 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]

**Comment by cowdude** [comment]
Hi,

Assuming the speedtest module is in your PYTHONPATH, you can invoke it that way:

```
python3 -m speedtest --version
speedtest-cli 2.1.2
Python 3.7.3 (default, Oct  7 2019, 12:56:13) [GCC 8.3.0]
```

Replace `python3` with the python executable you'd like to use.

If you get a `No module named speedtest` error, that means the module could not be found in your PYTHONPATH. In such case, I would strongly recommend that you setup a python2 virtualenv in order to properly (and painlessly) manage your python requirements against the version of python+pip of your liking.

**Comment by nielsroskam** [comment]
I am not sure if this issue has been fixed yet, but I found someone else with the same experience. The upload speed is incorrect when using python3. It is divided by a factor 10, or the decimal has been shifted left once. So it shows 3.8Mbps vs the actual 38Mbps. Using python2 it works well.
