### ISSUE TITLE
Speedtest-cli not working on Lenovo L420 Laptops

### ISSUE THREAD

**Issue by gseiki** [sivel/speedtest-cli#699]
Hi, I have more than a dozen Lenovo L420 laptops running Ubuntu 16.04 and 18.04 on my network. I also have a few MacBooks running Ubuntu 16.04 and 18.04 via VirtualBox.  I have one L420 on each of my 4 vlans running speed test every 10 minutes and sending the data to a mysql database.  Last week, the speed test on all 4 of these computers stopped working.  I thought maybe these four L420s got red flagged as bots.  But, that doesn't seem to be the case, as none of the L420's on my network can run speedtest-cli anymore.  Even computers that have never run speed test before.  The speedtest.net gui version doesn't work on any of my L420's either.  All L420s have working network connections. I was able to install and successfully run speedtest-cli on all of my Ubuntu VMs running on MacBooks.  Any ideas why my L420s can't run speedtest-cli anymore?

**Comment by sivel** [comment]
speedtest-cli builds a unique user agent, for the HTTP requests, that include platform information:

```
$ python -c 'import speedtest; print(speedtest.build_user_agent())'
Mozilla/5.0 (macOS-10.14.6-x86_64-i386-64bit; U; 64bit; en-us) Python/3.8.0 (KHTML, like Gecko) speedtest-cli/2.1.2
```

The only thing I can imagine is that Ookla for whatever reason has decided to block requests that contain a similar user agent string, due to abuse.

I have no affiliation with Ookla, but I do know that certain types of behavior violate their terms of service.  Your use may be excessive, and as such they have blocked you.
